name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "invalid","help wanted"]
projects: ["GamerSoft24/5"]
assignees:
  - GamerSoft24
  - SutoEXEC
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Opera or Opera GX
        - 360Chrome (Not from /InstallerSoft/.../360Chrome/)
        - 360Chrome (Humming Owl Version)
        - 360Chrome (bin-lr)
        - 360Chrome (bin-hb)
        - 360AFChrome (Not from /InstallerSoft/.../360Chrome/)
        - 360AFChrome (bin-2036r1af)
        - 360AFChrome (bin-af or af9)
        - 360AFChrome (bin-af5)
        - 360AFChrome (A1_1030rx)
        - 360AFChrome (A1_2036)
        - 360AFChrome (ABCD_1030rx)
        - 360AFChrome (bin-af4ABCD)
        - 360AFChrome (bin-af4G)
        - 360AFChrome (bin-af4JKQR)
        - 360AFChrome (bin-11af)
        - Mypal
        - ArcticFox
        - Supermium
        - None of the above :(
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/GamerSoft24/Software/blob/Main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
